export default {
  PERSON_API_ACKNOWLEDGE_FAILED_OPERATION: 'PERSON_API_ACKNOWLEDGE_FAILED_OPERATION',

  PERSON_API_SEARCH_PERSONS: 'PERSON_API_SEARCH_PERSONS',
  PERSON_API_SEARCH_PERSONS_SUCCEEDED: 'PERSON_API_SEARCH_PERSONS_SUCCEEDED',
  PERSON_API_SEARCH_PERSONS_FAILED: 'PERSON_API_SEARCH_PERSONS_FAILED',
  PERSON_API_SEARCH_PERSONS_IN_PROGRESS: 'PERSON_API_SEARCH_PERSONS_IN_PROGRESS',
  PERSON_API_ACKNOWLEDGE_SEARCH_PERSONS_OPERATION: 'PERSON_API_ACKNOWLEDGE_SEARCH_PERSONS_OPERATION',

  PERSON_API_DELETE_PERSON: 'PERSON_API_DELETE_PERSON',
  PERSON_API_DELETE_PERSON_SUCCEEDED: 'PERSON_API_DELETE_PERSON_SUCCEEDED',
  PERSON_API_DELETE_PERSON_FAILED: 'PERSON_API_DELETE_PERSON_FAILED',
  PERSON_API_DELETE_PERSON_IN_PROGRESS: 'PERSON_API_DELETE_PERSON_IN_PROGRESS',
  PERSON_API_ACKNOWLEDGE_DELETE_PERSON_OPERATION: 'PERSON_API_ACKNOWLEDGE_DELETE_PERSON_OPERATION',
};
