export default {
  LOCAL_STATE_SORT_COLUMN_CHANGED: 'LOCAL_STATE_SORT_COLUMN_CHANGED',
  LOCAL_STATE_SORT_ORDER_CHANGED: 'LOCAL_STATE_SORT_ORDER_CHANGED',
  LOCAL_STATE_PAGE_NUMBER_CHANGED: 'LOCAL_STATE_PAGE_NUMBER_CHANGED',
  LOCAL_STATE_ROWS_PER_PAGE_CHANGED: 'LOCAL_STATE_ROWS_PER_PAGE_CHANGED',
};
